### ISSUE TITLE
couldn't close file error

### ISSUE THREAD

**Issue by ltauxe** [bcych/BiCEP_GUI#4]
This is the error plaguing me now on my laptop installation: 

running it on the KEN data from the Levy festschrift on b09664a with deletion of first measurement.  

libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Couldn't close file

but the program did complete the processing, so not bad?  

lisa

**Comment by bcych** [comment]
This appears to be an interaction between python's multiprocessing options and mac catalina ([see this discussion on the pystan website](https://discourse.mc-stan.org/t/issues-with-pystan-multiprocessing-and-subsequently-the-pystan3-pre-release-on-mac-os-catalina/12798)). If the program completed running, it should be ok.

**Comment by ltauxe** [comment]
It didn’t complete- just hung there

**Comment by ltauxe** [comment]
Oh sorry this one did complete- the other one didn’t

**Comment by ltauxe** [comment]
ok. i’m trying it on the Shaar et al. 2011 data set now.  so far so good.  
lisa
