### ISSUE TITLE
hanging notebook with 'couldn't close' error bug still there

### ISSUE THREAD

**Issue by ltauxe** [bcych/BiCEP_GUI#7]
error on first specimen in the S16 data set:

 ** On entry to DLASCLS parameter number  5 had an illegal value
 ** On entry to DLASCLS parameter number  4 had an illegal value
.dylib: terminating with uncaught exception of type std::runtime_error: Couldn't close file
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Couldn't close file
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Couldn't close file

**Comment by bcych** [comment]
This is a bug with python's "multiprocessing" package on mac os catalina. Pystan forums suggest that this is a bug with matplotlib's font_manager.py. See: https://discourse.mc-stan.org/t/issues-with-pystan-multiprocessing-and-subsequently-the-pystan3-pre-release-on-mac-os-catalina/12798/14

**Comment by bcych** [comment]
Confirmed that doing the above fixed this problem. Please note that the `font_manager.py` file is located in `anaconda3/envs/BiCEP/lib/python3.7/site-packages/matplotlib/font_manager.py` wherever your anaconda directory is.
